### PR TITLE
Add charge bar to MendProjector

### PR DESCRIPTION
**Pull request by NiChrosia**

### CODE REVIEW

**Comment by NiChrosia** [comment]
..right, forgot about semicolons, currently cloning the repo so I can edit in IntelliJ rather than the web editor.

**Comment by NiChrosia** [comment]
94% progress on cloning

**Comment by NiChrosia** [comment]
...just realized this is the wrong repo.

**Comment by buthed010203** [comment]
i was waiting for that one lol

**Comment by NiChrosia** [comment]
still cloning the v6 client lol

**Comment by buthed010203** [comment]
yeah it uh takes a while to clone v6... have you tried [gitpod](https://gitpod.io)? takes way less time and you can just install the java extension and it works fine

**Comment by NiChrosia** [comment]
:eyes: currently looking at that

**Pull request closed without merging**
